// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Acknowledgment payload for daemon responses
 */
export type AckPayload = { request_id: string, success: boolean, error: string | null, };
