// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Session statistics captured at archive time
 */
export type ArchiveStatistics = { 
/**
 * Total message count
 */
message_count: number, 
/**
 * Total event count
 */
event_count: number, 
/**
 * Total permission requests count
 */
permission_count: number, 
/**
 * Session duration in seconds
 */
duration_seconds: number, };
