// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceType } from "./DeviceType";

/**
 * Client device information
 */
export type ClientDevice = { device_id: string, device_name: string, device_type: DeviceType, authorized_at: string, server_url: string, token_hash: string | null, last_seen_at: string | null, created_at: string, };
