// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client-to-server message types
 */
export type ClientToServer = { "type": "subscribe_session", "payload": { session_id: string, } } | { "type": "unsubscribe_session", "payload": { session_id: string, } } | { "type": "ping" };
