// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Archive close reason
 */
export type CloseReason = "user_closed" | "completed" | "failed" | "terminated";
