// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to create a new session
 */
export type CreateSessionRequest = { 
/**
 * Idempotency key for duplicate request protection
 */
idempotency_key: string, host_id: string, workspace_id: string, title: string, initial_message: string, };
