// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error payload for failed operations
 */
export type ErrorPayload = { request_id: string, error_code: string, error_message: string, };
