// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DaemonStatus } from "./DaemonStatus";
import type { OnlineStatus } from "./OnlineStatus";
import type { PairStatus } from "./PairStatus";
import type { Platform } from "./Platform";

/**
 * Remote host information
 */
export type Host = { host_id: string, host_name: string, platform: Platform, online_status: OnlineStatus, daemon_status: DaemonStatus, last_active_at: string | null, pair_status: PairStatus, pair_code: string | null, qr_payload: string | null, created_at: string, updated_at: string, };
