// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pagination parameters
 */
export type Pagination = { 
/**
 * Page number (1-indexed)
 */
page: number, 
/**
 * Items per page
 */
limit: number, };
