// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionStatus } from "./PermissionStatus";
import type { RiskType } from "./RiskType";

/**
 * Permission request information
 */
export type PermissionRequest = { permission_id: string, session_id: string, risk_type: RiskType, summary: string, target: string | null, created_at: string, status: PermissionStatus, responded_at: string | null, };
