// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response after device registration
 */
export type RegisterDeviceResponse = { device_id: string, token: string, };
