// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Permission risk type
 */
export type RiskType = "write_fs" | "exec_cmd" | "network";
