// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Workspace information
 */
export type Workspace = { workspace_id: string, host_id: string, path: string, display_name: string, is_favorited: boolean, last_used_at: string | null, exists_on_host: boolean, created_at: string, updated_at: string, };
